
server:
  port: 9090
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: contact-service
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true